tasks:
  - init: |
      # Install Volta
      curl https://get.volta.sh | bash &&
      export VOLTA_HOME="$HOME/.volta" &&
      export PATH="$VOLTA_HOME/bin:$PATH" &&
      volta install node@$(jq -r .engines.node package.json) &&
      
      # Install Meteor
      curl https://install.meteor.com/\?release\=3.0.4 | sh &&
      export PATH="$HOME/.meteor:$PATH" &&

      # Install Deno without prompts
      curl -fsSL https://deno.land/install.sh | sh &&
      export DENO_INSTALL="$HOME/.deno" &&
      export PATH="$DENO_INSTALL/bin:$PATH" &&
      

      # Install Yarn 
      yarn &&

      # Set ROOT_URL for development environment
      export ROOT_URL=$(gp url 3000)

    # Run build and dev scripts
    command: yarn build && yarn dsv   

ports:
  - port: 3000
    visibility: public
    onOpen: open-preview 

github:
  prebuilds:
    master: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true

vscode:
  extensions:
    - esbenp.prettier-vscode
